### ISSUE TITLE
diamond scrap mixels(?)

### ISSUE THREAD

**Issue by LonelyMusicDisc** [scaldings/gilded-netherite-fabric#2]
![diamond_scrap](https://user-images.githubusercontent.com/37805980/101277194-c8167f00-37c3-11eb-899c-dd1ec994364f.png)

I was kind of annoyed by the mixels in the scrap diamond sprite/texture

![diamond_scrap_2](https://user-images.githubusercontent.com/37805980/101277622-cac6a380-37c6-11eb-8150-6e6bbf4d3abc.png)

this is my shitty version without mixels. you get the idea :/

**Comment by scaldings** [comment]
I like it, that was just a temporary texture but nobody really cared. I like this one better. I will add it in the next update, as soon as I get access to my CurseForge account. Thank you!
