### ISSUE TITLE
[1.16.4-1.3.0-release] Dedicated Server Crash on load. 

### ISSUE THREAD

**Issue by JoelZBub** [scaldings/gilded-netherite-fabric#3]
Fabric version: 0.10.8
Fabric API version: 0.28.1+1.16
Gilded Netherite for Fabric version: 1.3.0

Issue: When starting fabric server with only Gilded Netherite and Fabric API installed, the server initialization stops with the following log file:
https://hatebin.com/qjjhsbjhqa

Client rendering classes attempting to load server side.

**Comment by scaldings** [comment]
This issue is solved in the next (1.4.0) update of this mod. Thank you for reporting this issue!
