### ISSUE TITLE
Incompatibility with GeckoLib

### ISSUE THREAD

**Issue by Snivine** [scaldings/gilded-netherite-fabric#5]
This is either Gilded Netherite is incompatible with GeckoLib, GeckoLib is incompatible with Gilded or GeckoLib is borke

anyway I'll post this issue on both GeckoLib and Gilded Netherite to make sure that both developers are aware of this issue

https://paste.ee/p/6CzLB

**Comment by Snivine** [comment]
bernie-g/geckolib#55

**Comment by scaldings** [comment]
This issue is caused by GeckoLib, not my mod. I will leave the issue to them since they bomb all the armor rendering mixins. Thank you for reporting this issue!
